### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by PenguinFlyingHigh** [EmceeEscher/Roy-the-Traffic-Cop#65]
I think I figured out where our memory leak is coming from, and it dates waaay back.

When we create a car, we use the init and allocate all that space. But when we delete a car, we only erase the car from the deque but not actually free it's resources. However, calling car.destroy() does some super funky stuff. Can't call delete either since it's not a pointer. I tried with free{&car[i]} but that causes placard to run into issues with it's pointer now being lost. Anyhow, using this to leave as a note for myself, but if someone also wants to take a crack at it, be my guest!

**Comment by EmceeEscher** [comment]
I remember talking about this way back when it was first implemented and I remember what we thought at the time was that the deque class would automatically handle the destruction of a member when it gets removed. I'm not confident enough in my C++ to know if that's true or not, though... What happens when you call car.destroy()? Could we just add a call to that immediately before we pop it from the deque? 

Also there's an issue with a placard that is potentially related. When I compile on Mac I get this warning:
```
src/car.cpp:171:2: warning: delete called on non-final 'Placard' that has
     virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
       delete m_turn_placard;
```
It's just a warning, not an error, and it didn't seem to have visible effects before, so I never dealt with it, but if it's causing issues now, then maybe I should.

However, I don't think either of these are what's causing the slowdown issues for @theochit because they've been in master forever. We should definitely find a fix for this, but I don't think it's a necessity for the milestone due on Monday night.

**Comment by PenguinFlyingHigh** [comment]
Definitely not for the milestone. I though `.erase()` should call the destructor, but since we're not creating cars with `new`, but rather using `.init()`, I don't know if erase is actually doing any destruction. Calling `car.destroy()` seems cause really funky graphical glitches and artifacts. Breaks the game visually.
